apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU1NQW9HQTFVRUF3d0RZbTlpTVJBd0RnWURWUVFLREFkc1pXRnlibVZ5TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbW4zalNqTCtlUnhTTnA5TTR6QkZ6ZmtFCm9KQk9RTUlsZGtLek9xdnVDYjg1UUVZaGlyVVRvT2ZIcEJ4L08yZ2JkN08vR0dxSld1YU1IemY5WndtRmlyYnEKYzZFb3BLZG5wSk5IZ2w0RW0yZUQxb1ZVZ2JNVjVSek43VEVFbnVzYlp4cVI3Vi95T2VCZS9kWGZQcmx2NnlDSgpQVlhIT1VzSnJQN293a0ZBWG4rYkUwZVJCSjRnNFYzd2RpbVg3UWc4R2liY2txVWdVcUtiNVMwcDlRQmcrampxCmpaWFl0Tlp0NURUeUpnSHR4azJjeWxReURKaWZvcCsxV1hFVjd5WlI1ZW9oaU5GbXRGbGpQeVV3OGVoMis2MlUKdjAzV3ZvcVlRSkxlbVBnQytaOUtsUHIxWUJTZW1wd1VpRzZUbVU5Vm4vaWNNZTJMSGptTU93dUtoalF1NHdJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCRWxJK0lwcUw4bnllU3cySjdrS2JRMEZlOXlkelA5ClZMUzdId2xIRHQ2MmJvaTczN3V0aVJoaWVUWG5ZK0Rrdnd5eFhrUy9TbE81NXRKOFU3QXRETGNGMnZ6dnNCazkKQmRCK2tyRTNPOUh4OG9iZ1NERFR2TFpDdnhPOE92OE9XOVB0T1A5WDl6anNwM0tvdU9rRWt5cG5ROTBvQjEzawp1YjVHMklCTnd4OU9LSC9IWVZRRjdaaE9uVFpTRlJybXRiRHQvZ1ZsOXJyekU2NEQ1TUtSVlBIMEsxN3Z2Z2dECjZZbUswb0NOc0Y0RHJwL3JnMXAyS0c1NzNLT1YvQ2p6bHlDR0ZwR21iYjBFWjVDemFZeWk3Q3p6VWVMUjU5ZXkKSm8zOUFoeElxenRCZlJPYWlXT0lnTU1ocytyREhqWW9vNzcvL08ydGFqOHhkdGxUd3BQaHZWUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg== 
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
